steps:
- id: download-serviceaccount
  name:  gcr.io/cloud-builders/gsutil
  args:
    - cp
    - gs://doccano-dev/sa/doccano-ai.key.json
    - .

- id: docker-build
  name: gcr.io/cloud-builders/docker
  args:
    - build
    - --tag=gcr.io/${PROJECT_ID}/mavencode-doccano:${BRANCH_NAME}
    - .
  wait_for:
    - download-serviceaccount

- id: docker-packaging
  name: gcr.io/cloud-builders/docker
  args:
    - push
    - gcr.io/${PROJECT_ID}/mavencode-doccano:${BRANCH_NAME}
  waitFor:
    - docker-build

#- id: docker-packaging
#  name: gcr.io/kaniko-project/executor:v0.20.0
#  args:
#    - --dockerfile=Dockerfile
#    - --destination=gcr.io/${PROJECT_ID}/mavencode-doccano:${BRANCH_NAME}
#    - --cache=true
#    - --cache-ttl=2h
#    - --cache-dir=
#  wait_for:
#    - download-serviceaccount


- id: deploy-runner
  name: gcr.io/cloud-builders/gcloud
  args:
    - beta
    - run
    - deploy
    - mavencode-doccano
    - --image
    - gcr.io/${PROJECT_ID}/mavencode-doccano:${BRANCH_NAME}
    - --region
    - us-central2
    - --memory
    - 1028Mi
    - --platform
    - managed
    - --allow-unauthenticated
    - --set-env-vars
    - ADMIN_USERNAME=mavencode
    - --set-env-vars
    - ADMIN_EMAIL=doccano@mavencode.com
    - --set-env-vars
    - ADMIN_PASSWORD=doccano
    - --set-env-vars
    - DB_NAME=doccano-dev
    - --set-env-vars
    - DB_USER=admin
    - --set-env-vars
    - DB_PASSWORD=admin
#    - DB_HOST=35.186.43.239
    - --set-env-vars
    - DB_HOST=127.0.0.1
    - --set-env-vars
    - DB_PORT=5432
  wait_for:
    - docker-packaging

options:
  machineType: N1_HIGHCPU_32